#security:  #配置spring-security功能
#  basic:
#    enabled: true  #开启用户登录权限验证
#  user:
#    name: admin   #设置登录用户为admin
#    password: admin #设置账号密码为admin
server:
  port: 9080
eureka:
  instance:
    hostname: localhost
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: false # \u8868\u793A\u662F\u5426\u6CE8\u518C\u81EA\u8EAB\u5230eureka\u670D\u52A1\u5668\uFF0C\u56E0\u4E3A\u5F53\u524D\u8FD9\u4E2A\u5E94\u7528\u5C31\u662Feureka\u670D\u52A1\u5668\uFF0C\u6CA1\u5FC5\u8981\u6CE8\u518C\u81EA\u8EAB\uFF0C\u6240\u4EE5\u8FD9\u91CC\u662Ffalse
    fetchRegistry: false
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 	

#application.propertis 配置文件写法
#server:
#  port:123456
#  
#eureka:
#  instance:
#	hostname: localhost
#	client:
#	eureka.client.register-with-eureka=false
#	eureka.client.fetch-registry=false
#		serviceUrl:
#      		defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      		defaultZone:http://localhost:${server.port}/eureka/